# Generated by Django 6.1.1 on 2026-10-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Client Phone Number')),
                ('telegram_id', models.BigIntegerField(verbose_name='Client Telegram ID')),
                ('total_spent', models.IntegerField(default=0, verbose_name='Total Spent')),
                ('last_operation_date', models.DateField(blank=True, null=True, verbose_name='Last Operation Date')),
                ('registered_at', models.DateField(auto_now_add=True, verbose_name='Registered Date')),
                ('custom_discount', models.FloatField(default=0.0, verbose_name='Custom Discount')),
                ('discount_value', models.FloatField(default=0.0, verbose_name='Discount Value')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('REFUND', 'Refund'), ('BONUS', 'Bonus')], default='PURCHASE', max_length=20, verbose_name='Operation Type')),
                ('amount', models.FloatField(default=0.0, verbose_name='Operation Amount')),
                ('operation_date', models.DateField(auto_now_add=True, verbose_name='Operation Date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lp_backend.client', verbose_name='Operation for -> ')),
            ],
        ),
    ]
