# Generated by Django 6.1.1 on 2026-10-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Client Phone Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Client Telegram ID'),
        ),
    ]
