# Generated by Django 6.1.1 on 2026-10-07 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp_backend', '0002_alter_client_phone_number_alter_client_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Discount Tier Name')),
                ('min_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, unique=True, verbose_name='Minimum Discount Total')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Discount Percentage')),
            ],
            options={
                'ordering': ['-min_total'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='discount_value',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount Tier'),
        ),
        migrations.AlterField(
            model_name='client',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total Spent'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Operation Amount'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lp_backend.client', verbose_name='Operation for -> '),
        ),
    ]
