# Generated by Django 6.1.1 on 2026-10-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp_backend', '0003_discounttier_alter_client_discount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total Spent'),
        ),
        migrations.AlterField(
            model_name='discounttier',
            name='min_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, unique=True, verbose_name='Minimum Discount Total'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Operation Amount'),
        ),
    ]
