# Generated by Django 6.1.1 on 2026-10-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lp_backend', '0004_alter_client_total_spent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='discount_value',
        ),
    ]
